name: Publish BlueGraph to PyPI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Build and publish on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build a source tarball
        run: python setup.py sdist
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          username: 'bbp.opensource'
          password: ${{ secrets.PYPI_API_TOKEN }}
