name: Test BlueGraph
on:
    pull_request:
    push:
      branches:
        - master
        - github-action-test
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get Neo4j from a third party repo and install
        run: |
          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt-get update
          wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
          echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
          sudo apt-get update
          sudo apt-get install neo4j=1:4.4.3
      - name: Download the graph data science lib
        run: |
          wget https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/neo4j-graph-data-science-1.8.2-standalone.zip
          unzip neo4j-graph-data-science-1.8.2-standalone.zip
          sudo cp neo4j-graph-data-science-1.8.2.jar /var/lib/neo4j/plugins/
      - name: Add conda to system path
        run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            echo $CONDA/bin >> $GITHUB_PATH
      - name: Useful for debugging any issues with conda
        run: conda info -a
      - name: Update the base env with graph-tool and faiss-gpu installed from conda-forge
        run: |
           conda install python=${{ matrix.python-version }}
           conda env update --file test-environment.yml --name base
      - name: Install the rest of the dependencies
        run: |
          python3 -m pip install .[dev]
      - name: Configure the Neo4j database
        run: |
          sudo neo4j-admin set-initial-password neo4j
          echo 'dbms.connector.bolt.listen_address=0.0.0.0:7687' | sudo tee -a /etc/neo4j/neo4j.conf
          echo 'dbms.security.procedures.unrestricted=gds.*' | sudo tee -a /etc/neo4j/neo4j.conf
          echo 'dbms.security.procedures.whitelist=gds.*' | sudo tee -a /etc/neo4j/neo4j.conf
          cat /etc/neo4j/neo4j.conf
      - name: Start a db instance and wait (it takes time to start)
        run: |
          sudo service neo4j restart
          sleep 60
      - name: Test with pytest
        run: |
          pytest --cov=./bluegraph
      - name: Upload to codecov
        if: ${{matrix.python-version == '3.7'}}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: pytest
          name: "bluegraph-py37"
